# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.AddField(
            model_name='person',
            name='identity',
            field=models.CharField(choices=[('Worker', 'DepartMent Worker'), ('Depart', 'DepartMent Leader'), ('Center', 'Center Leader'), ('Company', 'Company Leader')], default='Worker', max_length=1),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='name', max_length=60),
        ),
    ]
