# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160918_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='identity',
            field=models.CharField(choices=[('Worker', 'DepartMent Worker'), ('Depart', 'DepartMent Leader'), ('Center', 'Center Leader'), ('Company', 'Company Leader')], default='Worker', max_length=20),
        ),
    ]
