# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160918_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=polls.models.user_directory_path)),
            ],
        ),
    ]
