# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 06:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_choice_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='person',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
