# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 06:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0008_auto_20160919_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='person',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
