# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_question_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doc',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
