# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20160920_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.Question')),
                ('stop_date', models.DateField(verbose_name='date stop')),
            ],
            bases=('polls.question',),
        ),
    ]
