# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='doc',
            name='doctype',
            field=models.ManyToManyField(to='polls.DocType'),
        ),
    ]
