# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20160921_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
