# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_doc_is_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='is_activated',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4f7f\u7528'),
        ),
    ]
